# 复用的 SSL 配置片段
# 在各 server 块中用 include conf.d/_ssl.conf; 引入

ssl_certificate     /etc/letsencrypt/live/darkchunk.top/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/darkchunk.top/privkey.pem;
ssl_protocols       TLSv1.2 TLSv1.3;
ssl_ciphers         HIGH:!aNULL:!MD5;
ssl_session_cache   shared:SSL:10m;
